"use client";
import Advertisement from '@/components/organism/advertisement/Advertisement'
import PostOverlayCard from '@/components/molecules/card/PostOverlayCard'
import PostCard from '@/components/molecules/card/PostCard'
import PageInfo from '@/components/organism/pageInfo/PageInfo'
import React, {useEffect, useState} from 'react'
import api from "@/utils/api";

// export const metadata = {
//    title: 'Blog Page | ',
//    description: 'Generated by create next app',
// }

const BlogListing = () => {

   const [blogData, setBlogData] = useState([]);

   useEffect(() => {
      // Verileri API'den al
      api.get('/blogs')
          .then((res) => {
             // Veriyi state'e kaydet
             setBlogData(res.data.blogs);
          })
          .catch((error) => {
             console.error('Error fetching blog data:', error);
          });
   }, []);

   return (
      <main>
         <div className="container mx-auto">
            {/* Page title info */}
            <section>
               <PageInfo />
            </section>

            {/* Banner */}
            <section className="my-12">
               <PostOverlayCard />
            </section>

            {/* All posts component */}
            <section className="my-20">
               <div className=" grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
                  {blogData.map((item, index) => (
                      <PostCard key={index} data={item} />
                  ))}
               </div>
               <div className="flex items-center justify-center w-full mt-8">
                  <button className="btn btn-outline btn-secondary font-work px-5 text-base font-medium">
                     Load More
                  </button>
               </div>
            </section>

         </div>
      </main>
   )
}

export default BlogListing
