"use client";

import React, { useState, useEffect } from 'react';
import BannerCard from '@/components/molecules/card/BannerCard'
import PostCard from '@/components/molecules/card/PostCard'
import Link from 'next/link'
import api from '../utils/api'

// export const metadata = {
//    title: 'Home Page | ',
//    description: 'Generated by create next app',
// }

export default function Home() {
    const [blogData, setBlogData] = useState([]);

    useEffect(() => {
        // Verileri API'den al
        api.get('/blogs')
            .then((res) => {
                // Veriyi state'e kaydet
                setBlogData(res.data.blogs);
            })
            .catch((error) => {
                console.error('Error fetching blog data:', error);
            });
    }, []);

    return (
        <main className="container mx-auto">
            {/* Banner Component */}
            <section>
                <BannerCard  data={blogData[0]} />
            </section>

            <section className="my-20">
                <h3 className="text-base-content font-bold text-2xl mb-8 font-work leading-8">
                    Latest Post
                </h3>
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
                    {blogData.map((item, index) => (
                        <PostCard key={index} data={item} />
                    ))}
                </div>
                <div className="flex items-center justify-center w-full mt-8">
                    <Link
                        href={`/blog`}
                        className="btn btn-outline btn-secondary text-secondary-content/60 font-work font-medium text-base"
                    >
                        View All Post
                    </Link>
                </div>
            </section>
        </main>
    );
}
