"use client";

import AuthorInfo from '@/components/organism/authorInfo/AuthorInfo'
import PostCard from '@/components/molecules/card/PostCard'
import React, {useEffect, useState} from 'react'
import api from "@/utils/api";

// export const metadata = {
//    title: 'Author Page | ',
//    description: 'Generated by create next app',
// }

const Author = () => {
    const [blogData, setBlogData] = useState([]);

    useEffect(() => {
        // Verileri API'den al
        api.get('/blogs')
            .then((res) => {
                // Veriyi state'e kaydet
                setBlogData(res.data.blogs);
            })
            .catch((error) => {
                console.error('Error fetching blog data:', error);
            });
    }, []);
    return (
      <main>
         {/* Author info */}
         <section>
            <AuthorInfo />
         </section>

         {/* Latest Post */}
         <section>
            <div className="container mx-auto mt-12 mb-24 px-5 sm:px-0">
               <h3 className="text-base-content font-bold text-2xl mb-8">
                  Latest Post
               </h3>
               <div className=" grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
                   {blogData.map((item, index) => (
                       <PostCard key={index} data={item} />
                   ))}
               </div>
            </div>
         </section>
      </main>
   )
}

export default Author
